### ISSUE TITLE
Calibration of module does not work

### ISSUE THREAD

**Issue by genfersee** [adfinis-sygroup/sbb-fallblatt#4]
Hello!

I am trying to recalibrate a module since the amount of pulses sent for a step is too low.
I have tried to follow the steps you mentioned:

1. Send calibration command to the module withh address 22: <ff cc 16> 
2. Send step command to the module with address 22 in order to make blade to fall:  <ff c6 16> 
3. Send pulse commands to the module with address 22 until next blade falls:  <ff c7 16> 
4. Send win command to the module with address 22 in order to close (?) the calibration on position 00 <ff cb 16 00>

After doing that, the amount of pulses for a step seems to remain same as before. What am I doing wring? :)

Thanks in advance and kind regards!

**Comment by genfersee** [comment]
Oh, I just saw the python files in this repository, let me try out and I will update this one.

**Comment by genfersee** [comment]
Hello!
What is the exact purpose of calibration process:  is it adapting the number of pulses within a step for a given module, and program this number of pulses value in the module board?

**Comment by eni23** [comment]
> is the exact purpose of calibration process: is it adapting the number of pulses within a step for a given module, and program this number of pulses value in the module board?

Yes correctly. It is also used to set the zero position of the module. If you want to change numbers of blades, you need to send the `TYPE` command..

**Comment by genfersee** [comment]
Could you please tell me more about this TYPE command? I see in your doc it is for hours or minutes? My modules are not "hour" nor "minute" modules but "train types" and "information messages".
When should I send this TYPE command if I want to reajust the number of pulses for a step?
1 module board is dead and I want to replace it with the module board of another module. This is why I need to readapt the number of pulses for a step inside this module board.
Thanks in adance! :)

**Comment by genfersee** [comment]
Ohh I see! There are only 2 types: 40 or 62 blades! So I have to send the TYPE command 1 to my module which has only 40 blades :):) Thanks! I will try tonight.

**Comment by genfersee** [comment]
I could successfully change module type and recalibrate it. Many thanks!
