### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by genfersee** [adfinis-sygroup/sbb-fallblatt#6]
Dear team,

I am trying to install your program but did no manage.
Could you please provide some instructions to install the program? Is this Python 2 or 3?

Thanks in advance!
Genfersee

**Comment by genfersee** [comment]
Hello :)

I managed to install the package by doing:
`python3 setup.py install --user`

How can I launch the clock module?

**Comment by eni23** [comment]
This repo does only contain a ready to use python-module and mostly docs how its working. The scripts for clock and so on need to be implemented by yourself. But there are a few examples in the python-module-directory. 

For a clock you need to do the following:

* Copy the content from this file somewhere on your computer: https://github.com/adfinis-sygroup/sbb-fallblatt/blob/master/sbb_fallblatt/clock.py
* Adjust the addresses for your modules (`SBB_MODULE_ADDR_HOUR` and `SBB_MODULE_ADDR_MIN`)
* Change the import of the sbb_rs485 module to (if you have installed it via setup.py):
```
import sbb_rs485
```
* Run the file

**Comment by genfersee** [comment]
Thanks!

I have tried but got the following error:
`
python3 clock.py 

Traceback (most recent call last):
  File "clock.py", line 25, in <module>
    main()
  File "clock.py", line 18, in main
    clock.set_time_now()
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 277, in set_time_now
    self.set_time(now.hour, now.minute)
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 271, in set_time
    self.set_hour(hour)
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 266, in set_hour
    hour
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 113, in set_position
    pos
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 68, in send_msg
    self.set_break()
  File "/Users/Yohann/Desktop/sbb-fallblatt-master/sbb_fallblatt/sbb_rs485.py", line 60, in set_break
    self.serial.break_condition = True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyserial-3.4-py3.6.egg/serial/serialutil.py", line 479, in break_condition
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyserial-3.4-py3.6.egg/serial/serialposix.py", line 620, in _update_break_state
OSError: [Errno 25] Inappropriate ioctl for device
`

**Comment by eni23** [comment]
The example and the module assume that the USB->RS485 adapter is connected to `/dev/ttyUSB0`. If this is not the case, you can change it while constructing the `PanelClockControl` object:

```python
clock = sbb_rs485.PanelClockControl(
    port="/dev/ttyUSBwhatever",
    addr_hour = SBB_MODULE_ADDR_HOUR,
    addr_min  = SBB_MODULE_ADDR_MIN
)
```

Also make sure that you have enough permissions for the port to use.

**Comment by genfersee** [comment]
I got exact same errors as above on another setup by running :
`python3 clock.py`

I assume your code is in Python 3 , correct?

**Comment by eni23** [comment]
Yes, the code is in python3. 

```
OSError: [Errno 25] Inappropriate ioctl for device
```
looks like your serial adapter seems to have problems with sending break conditions over pyserial. Im afraid i cant really help here with that less informations about your enviroment..

**Comment by genfersee** [comment]
Thanks!
In fact, I am trying to write my own clock Python program. My hour module address is 6 and my minute module address is 7. Both modules are connected to my SparkFun USB to RS-485 Converter.

With the following code, I am able to command the hour module without any problem. But the minute module only reacts a few time and in inconsistent way...

`import sys`
`import serial`
`import serial.rs485`
`try:`
`   ser = serial.Serial(port='/dev/tty.usbserial-A90806FR', baudrate=19200)`
`   print("Opening serial port: OK\n")`
`except:`
`   print("Opening serial port: FAILED\n")`
`   ser = False`
`ser.write(b'\xff\xc0\x07\x03')`

When I use another existing program based on nodejs, both hour or minute modules are working great, so I believe my HW installation is ok!

This is why I wanted to try with your clock program, and see if it works better, but I faced the issue described above.

Maybe my program is just missing a simple command or something to have the minute module work correctly?

Thanks in advance :)
Genfersee

**Comment by eni23** [comment]
It is weird that this is working. According to my reverse-engineering and a lot of tests the module excepts a break condition before sending a command to the module. Otherwise the modules never responded to any command. And i tried with multiple adapters with different chipsets. Maybe it works the first time since opening a serial port can look like a break condition.

The error you posted looks like our code seems to fail on setting a break condition:
https://github.com/adfinis-sygroup/sbb-fallblatt/blob/master/sbb_fallblatt/sbb_rs485.py#L59

Can you try to add the following to your code before sending the command and see if it works:
```python
ser.send_break()
ser.write(b'\xff\xc0\x07\x03')
```

If this will fail, it looks like a problem with pyserial. After a bit of googling it seems to be a bug which was recently fixed: https://github.com/pyserial/pyserial/pull/367 and you could try to update the pyserial module.

I never had this issue on Linux (also not on Raspberry PI), but normally i install the pyserial module directly over PIP and not via package manager.

I hope this helps.

**Comment by genfersee** [comment]
Hi!

I got it working now on both modules with the following:

`ser.send_break()
time.sleep(0.003)
ser.write(bytes(chr(0xFF)+chr(0xC0)+chr(hourModuleAddress)+chr(int(currentHourString)+1)))
time.sleep(0.003)
ser.send_break()
time.sleep(0.003)
ser.write(bytes(chr(0xFF)+chr(0xC0)+chr(minuteModuleAddress)+chr(int(currentMinuteString)+1)))`

Thanks you so much for your support, you can close the issue :)
Kind regards,
Genfersee

**Comment by eni23** [comment]
Perfect :)

FYI: you can specify a duration with the send_break function, so you can omit the time.sleep statement:
```python
ser.send_break(0.3)
```
Source: https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.send_break
