### ISSUE TITLE
Documentation about old displays

### ISSUE THREAD

**Issue by jpfaff** [adfinis-sygroup/sbb-fallblatt#7]
Hello,
I have collected some information about the old SBB flip flap displays as well as what I think is an intermediate step between the old ones and the new ones.
Is this repository still in use and are you interested in that kind of documentation? If so I could clean it up and create a pull request.

**Comment by karras** [comment]
Sounds good to me. I'd suggest that your PR doesn't remove the old ones but simply adds the ones that are missing. @eni23  What's your take on this?

**Comment by eni23** [comment]
The repo is still in use and of course im very happy if you are adding more infos about different hardware. 

thanks in advance!

**Comment by hairmare** [comment]
Fixed in #8
